# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coffeesnipe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Coffeesnipe

  target 'Coffeesnipe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeesnipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Coffeesnipe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Coffeesnipe-tvOS

  target 'Coffeesnipe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
